
leftDelim: '~{'
rightDelim: '}~'
inputDir: .templates/
outputDir: .
datasources:
  local:
    url: vars.techxchange.yaml
  terraform:
    url: ../terraform-modular-demo-framework/tf_output_vars.yaml
