---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volterra-ingress-controller
  namespace: {{ (datasource "local").XC_NAMESPACE }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/volterra-ingress-controller
    repoURL: https://github.com/{{ (datasource "local").REPO_OWNER }}/edgar-appstack-ce-infra.git
    targetRevision: HEAD
  destination:
    namespace: volt-ic
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
