---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: ~{ (datasource "terraform").namespace }~
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/grafana
    repoURL: https://github.com/~{ (datasource "local").repo_owner }~/~{ (datasource "local").repo }~.git
    targetRevision: HEAD
  destination:
    namespace: ~{ (datasource "terraform").namespace }~
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
