---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volterra-ingress-controller
  namespace: ~{ (datasource "terraform").namespace }~
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/volterra-ingress-controller
    repoURL: https://github.com/~{ env.Getenv "GITHUB_USER" }~/~{ (datasource "local").repo }~.git
    targetRevision: HEAD
  destination:
    namespace: ~{ (datasource "terraform").volt_ic_namespace }~
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
